//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joole_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProjtoProds = new HashSet<ProjtoProd>();
        }
    
        public int Product_Id { get; set; }
        public int SubCategory_Id { get; set; }
        public string Product_Name { get; set; }
        public string Product_Image { get; set; }
        public string Series { get; set; }
        public string Model { get; set; }
        public string Model_Year { get; set; }
        public string Series_Info { get; set; }
        public string Featured { get; set; }
        public string UseType { get; set; }
        public string Application { get; set; }
        public string Mount { get; set; }
        public string Accessories { get; set; }
        public string AirFlow { get; set; }
        public string MinPower { get; set; }
        public string MaxPower { get; set; }
        public string MinVolt { get; set; }
        public string MaxVolt { get; set; }
        public string MinRPM { get; set; }
        public string MaxRPM { get; set; }
        public string Speeds { get; set; }
        public string Sound { get; set; }
        public string Sweep { get; set; }
        public string MinHeight { get; set; }
        public string MaxHeight { get; set; }
        public string Weight { get; set; }
    
        public virtual SubCategory SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjtoProd> ProjtoProds { get; set; }
    }
}
